export const BUTTONS = {
  UP: 'XINPUT_GAMEPAD_DPAD_UP',
  DOWN: 'XINPUT_GAMEPAD_DPAD_DOWN',
  LEFT: 'XINPUT_GAMEPAD_DPAD_LEFT',
  RIGHT: 'XINPUT_GAMEPAD_DPAD_RIGHT',
  START: 'XINPUT_GAMEPAD_START',
  BACK: 'XINPUT_GAMEPAD_BACK',
  A: 'XINPUT_GAMEPAD_A',
  B: 'XINPUT_GAMEPAD_B',
  X: 'XINPUT_GAMEPAD_X',
  Y: 'XINPUT_GAMEPAD_Y',
  LEFT_THUMB: 'XINPUT_GAMEPAD_LEFT_THUMB',
  RIGHT_THUMB: 'XINPUT_GAMEPAD_RIGHT_THUMB',
  LEFT_SHOULDER: 'XINPUT_GAMEPAD_LEFT_SHOULDER',
  RIGHT_SHOULDER: 'XINPUT_GAMEPAD_RIGHT_SHOULDER'
}

export const AXES = {
  LEFT_X: 'XINPUT_GAMEPAD_LEFT_THUMB_X',
  LEFT_Y: 'XINPUT_GAMEPAD_LEFT_THUMB_Y',
  RIGHT_X: 'XINPUT_GAMEPAD_RIGHT_THUMB_X',
  RIGHT_Y: 'XINPUT_GAMEPAD_RIGHT_THUMB_Y',
  LEFT_TRIGGER: 'XINPUT_GAMEPAD_LEFT_TRIGGER',
  RIGHT_TRIGGER: 'XINPUT_GAMEPAD_RIGHT_TRIGGER'
}

export const AXES_VALUE_RANGES = {
  THUMB: {
    MIN: -32768,
    MAX: 32767
  },
  TRIGGER: {
    MIN: 0,
    MAX: 255
  }
}
